# This file can be used to create a conda environment named decision-tree-example to run the code for this project.

# NOTE: these commands assume the _configs directory is in the root of the project.  If it is not, you will need to adjust the paths accordingly.
# To create the environment, run: (this can take some time to run)
# 
#     conda env create -f _config/environment.yml
#
# After creating the environment, activate it using:
#
#     conda activate decision-tree-example
#
# If you need to delete the environment, run:
#
#     conda env remove --name decision-tree-example
#
# This will set up your environment with the specified dependencies.

name: decision-tree-example
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - jupyter 
      - ipykernel
      - notebook
      - ipywidgets
      - matplotlib
      - pandas
      - numpy
      - scikit-learn
      - seaborn
